export const GET_PLAYLIST_SUCCESS = 'GET_PLAYLIST_SUCCESS';
export const GET_PLAYLIST_FAILURE = 'GET_PLAYLIST_FAILURE';
export const GET_PLAYLIST_REQUEST = 'GET_PLAYLIST_REQUEST';

export const GET_TRACKS_REQUEST = 'GET_TRACKS_REQUEST';
export const GET_TRACKS_SUCCESS = 'GET_TRACKS_SUCCESS';
export const GET_TRACKS_FAILURE = 'GET_TRACKS_FAILURE';

export const GET_PLAYLIST_INFO_REQUEST = 'GET_PLAYLIST_INFO_REQUEST';
export const GET_PLAYLIST_INFO_FAILURE = 'GET_PLAYLIST_INFO_FAILURE';
export const GET_PLAYLIST_INFO_SUCCESS = 'GET_PLAYLIST_INFO_SUCCESS';


export const SET_PLAY = 'SET_PLAY';
export const SET_PLAY_REQUEST = 'SET_PLAY_REQUEST';
export const SET_PAUSE = 'SET_PAUSE';
export const SET_PAUSE_REQUEST = 'SET_PAUSE_REQUEST';
export const SET_SOURCE = 'SET_SOURCE';


export const PLAYING = 'PLAYING';
export const PAUSED = 'PAUSED';

export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_CURRENT_TRACK_REQUEST = 'SET_CURRENT_TRACK_REQUEST';

export const SET_QUEUE = 'SET_QUEUE_TRACK';
export const SET_QUEUE_REQUEST = 'SET_QUEUE_REQUEST';
